#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by the Gradle wrapper
##############################################################################

APP_HOME="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Gradle"
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

JAVACMD="$(which java)"

exec "$JAVACMD" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
